import { KageLandingPage } from '@designcodeio/threeui'
import '@designcodeio/threeui/style.css'

/**
 * ThreeUI <KageLandingPage /> with the configured props.
 * It renders /landing-pages/kage.html (public/) in a sandboxed iframe and injects
 * these typography settings into it. The page itself is the portfolio reskin
 * generated by vendor/threeui/reskin-kage.py.
 */
export function Scene() {
  return (
    <div className="shader-frame">
      <KageLandingPage
        headingFont="onest"
        bodyFont="onest"
        headingWeight="400"
        bodyWeight="300"
        primaryColor="#e0231c"
        headingSize={46}
        bodySize={17}
        headingLetterSpacing={-0.012}
      />
    </div>
  )
}
